In [1]:
import numpy as np
import pykasso.tools as pkt

### GEOLOGY
gslib_geology = pkt.GSLIB('test/inputs/betteraz_2D_z430.gslib')
geology = gslib_geology.export_column('intersect3', (300,300))
geology = np.repeat(geology[:, :, np.newaxis], 20, axis=2)

# for i in range(0,290,10):
#     geology[:, i+0, 19] = 0
#     geology[:, i+1, 19] = 0
#     geology[:, i+2, 19] = 0

### TOPOGRAPHY
topography = np.full((300,300), 350)
topography[:, 100:200] = 250
topography[100:200, :] = 250

### BEDROCK ELEVATION
bedrock_elevation = np.full((300,300), 50)
bedrock_elevation[:, 10:100] = 25

### WATER LEVEL ELEVATION
water_level_elevation = np.full((300,300), 200)
water_level_elevation[200:299, :] = 150

sks_settings = {
    'grid' : {
        'x0' : 572510,
        'y0' : 250010,
        'z0' : 0,
        'nx' : 300,
        'ny' : 300,
        'nz' : 20,
        'dx' : 20,
        'dy' : 20,
        'dz' : 20
    },
    'domain' : {
        'delimitation' : 'test/inputs/betteraz_polygon.txt',
        # 'topography'   : topography,
        # 'bedrock'      : bedrock_elevation,
        'water_level'  : water_level_elevation,
    },
    'geology' : {
        # 'data' : 'test/inputs/betteraz_2D_z430.gslib',
        'data' : geology,
        # 'cost': {1: 0.5, 2: 0.7}
    },
    # 'faults' : {
    #     'data' : 'test/inputs/faults.png',
    #     'axis': 'z',
        # 'cost': {1: 0.3, 2: 0.4}
    # },
    'fmm' : {
        'algorithm' : 'Isotropic3',
        'cost' : {
            'ratio' : 0.5
        },
    },
    'sks' : {
        'seed' : 0,
        'domain_from_geology' : False,
    },
    'verbosity' : {
        'logging'  : 0,
        'agd'      : 0,
        'karstnet' : 0
    },
    'outlets' : {
        'number'     : 100,
        # 'data'       : 'test/inputs/points.txt',
        'data'       : [[100,100], [200,200], [300,300], [4000,4000]],
        # 'data' : '',
        # 'shuffle'    : False,
        'importance' : [1,1,1],
        'mode' : 'uniform',
        # 'geology'    : [1],
        'seed' : 2,
        # 'x' : 'lambda : 1500 + 1500 * rng.random() * grid.dx',
        # 'y' : 'lambda : 1500 + 1500 * rng.random() * grid.dy',
        # 'z' : 'lambda : grid.z0'
    },
    'inlets' : {
        'number' : 100,
        # 'data'       : [],
        # 'shuffle'    : False,
        'per_outlet' : [5,5,5],
        'importance' : [1,1,1],
        'mode' : 'uniform',
        # 'geology'    : [2],
        'seed' : 1,
        # 'z' : 'lambda x, y : x + y'
    },
    # 'fractures': {
    #     'data': 'generator',
    #     'axis': 'z',
    #     'seed': 534106,
    #     'settings': {
    #         'family_01': {
    #             'alpha'        : 2,
    #             'density'      : 0.00001,
    #             'orientation'  : [340, 20],
    #             'dip'          : [80, 90],
    #             'length'       : [1000, 2000],
    #         }, 
    #         'family_02': {
    #             'alpha'        : 2,
    #             'density'      : 0.00001,
    #             'orientation'  : [340, 20],
    #             'dip'          : [0, 10],
    #             'length'       : [1000, 2000],
    #         }
        # }
    # },
}

In [2]:
import numpy as np
import pykasso as pk
pk.create_project('test')

debug_level = {
    'model'      : 4,
    'simulation' : 1,
    'iteration'  : 1,
}

for _ in range(1):
    sim = pk.SKS(debug_level=debug_level, sks_settings=sks_settings)
    # sim = pk.SKS(sks_settings=sks_settings)
    # sim = pk.SKS(debug_level=debug_level)
    # sim = pk.SKS()
    sim.build_model()
#     # sim.compute_karst_network()

CAUTION: You are using the development version of this package.
[[205 226   7]
 [ 95 179   9]
 [ 62 203  19]
 [103  98   3]
 [125 206   4]
 [200 122  17]
 [133  37  14]
 [ 59  64  10]
 [110 146   4]
 [160 207  16]
 [199 238   9]
 [183 135  18]
 [267 193   6]
 [ 80  72  16]
 [217 167   7]
 [ 50 150  16]
 [153  52  18]
 [ 98 137   8]
 [ 82 222   3]
 [171  97   9]
 [104 179   7]
 [153 198  13]
 [ 95 127   1]
 [ 71 199  10]
 [187  78  17]
 [129 127   3]
 [175  39   5]
 [173 116  11]
 [239 241   6]
 [127 151  18]
 [ 86 209  10]
 [166 222  11]
 [235 235  18]
 [249 220   0]
 [213 227   5]
 [175 196   6]
 [119 118   6]
 [121 157  12]
 [ 46 201   7]
 [ 79 216   8]
 [110  77  16]
 [112 179  19]
 [157  55  19]
 [144  85   5]
 [177 112   6]
 [220 203  12]
 [216 175  17]
 [192  82  17]
 [254 215  18]
 [107  87   7]
 [225 228  15]
 [231 223  11]
 [ 87 185  13]
 [136 172   7]
 [155  70   3]
 [177 159   4]
 [178 182  17]
 [ 62 128   5]
 [137 198   5]
 [ 61 195   2]
 [245 179   5]
 [ 83  74   4]
 [132 

NameError: name 'i' is not defined

In [7]:
import numpy as np
i,j,k = np.indices(sim.domain.data_volume.shape)
i,j,k = i.flatten(), j.flatten(), k.flatten(), 
state = sim.domain.data_volume.flatten()
nodes = list(zip(state, i, j, k))
probability_map = [(i,j,k) for (state,i,j,k) in nodes if state == 1]

indices = sim.rng['master'].choice(probability_map, size=100)
i,j,k = zip(*indices)
i

(189,
 99,
 183,
 199,
 50,
 53,
 124,
 145,
 201,
 60,
 71,
 107,
 166,
 217,
 53,
 157,
 99,
 198,
 153,
 71,
 244,
 48,
 190,
 30,
 60,
 104,
 215,
 218,
 75,
 60,
 59,
 194,
 127,
 41,
 223,
 197,
 170,
 66,
 83,
 173,
 93,
 82,
 213,
 116,
 75,
 40,
 53,
 102,
 147,
 55,
 114,
 82,
 193,
 172,
 158,
 179,
 105,
 174,
 188,
 116,
 193,
 212,
 133,
 78,
 239,
 52,
 232,
 134,
 119,
 188,
 154,
 133,
 185,
 148,
 54,
 115,
 167,
 199,
 213,
 229,
 187,
 191,
 172,
 190,
 183,
 168,
 223,
 71,
 191,
 98,
 133,
 269,
 163,
 256,
 219,
 169,
 81,
 226,
 163,
 60)

In [ ]:
# import pykasso.visualization as pkv
# pkv.show_array() 
# TODO affichage des coleurs par numero 
# pkv.show_array(sim.conceptual_model.data_volume)

In [ ]:
# import matplotlib.pyplot as plt
# f = plt.figure()
# plt.imshow(sim.domain.data_surface)
# plt.colorbar()

In [ ]:
import numpy as np
import pykasso.visualization as pkv

settings = {
    # 'show_grid' : True,
    'ghost'     : [0],
    # 'slice'     : True,
    'domain'    : True,
    'inlets'    : True,
    'outlets'   : True,
    # 'iteration' : 0
    # 'tracers'   : True,
}
pkv.show(sim, feature='grid', engine='pyvista', settings=settings)
# bedrock_elevation
# # TODO - show a specific fracture family

In [ ]:
import pyvista as pv
points = sim.inlets
points = points[['x', 'y', 'z']].values
points = points.astype('float32')
# print(points)
cloud  = pv.wrap(points)
# cloud

plotter = pv.Plotter()
plotter.add_points(cloud, render_points_as_spheres=False,)# point_size=20 , color='r')
plotter.show(cpos='xy')

In [ ]:
import numpy as np
import pykasso.visualization as pkv

steps = {
    1 : 'model',
    2 : 'fmm'
}
choice = 2

settings = {
    'iterations' : [0,2,4]
}

pkv.debug(sim, step=steps[choice], engine='pyvista', settings=settings)

# TODO

In [ ]:
### pyKasso

    ### general
    # -> Tests pour tous les attributs de SKS_SETTINGS : verbosity / piezometric_level
    # -> implémenter les volumes  : anisotropie avec pendage ???
    # -> collection d'exemples géométriques
    # -> méthode pour ajouter une étude de cas

    ### documentation / code
    # expliciter les sorties de fonctions

    ### tools - dev
    # 50% cProfile system
    # wrapper? : time process measurements (SKS, initilization, modelisation, each iteration?)

    ### tools - user
    # Geology editor ?
    # Topography editor ?
    # Water surface level editor ?
    
    ### visualization
    # wrapper gif

### futur
# mutli-processing
# add timing with UTC 

# Questions

In [ ]:
### Modeling
# Definition du domaine
# -> 'Domain' : quelles règles pour 'delimitation' / 'bedrock' / 'topography' ???
# -> topo et bedrock n'ont pas le droit de couper verticalement le modèle... ? 
# Bedding / faults / fractures
# -> un objet par couche, ou un objet qui agglomère tout ?

### Fast-marching
# Combien d'itération au total ? 
# Comment 'per_outlet' doit être contrôlé ?

### Management
# Structure du fichier d'output ?
# Noms des fonctions publiques ?

In [ ]:
# def get_surfaced_volume(direction:str):
#     if direction in ['weast', 'east']:
#         i = sim.domain.surfaces[direction]
#         print(i.shape)
#         j, k = np.indices(i.shape)
#     elif direction in ['north', 'south']:
#         j = sim.domain.surfaces[direction]
#         print(j.shape)
#         i, k = np.indices(j.shape)
#     elif direction in ['up', 'down']:
#         k = sim.domain.surfaces[direction]
#         print(k.shape)
#         i, j = np.indices(k.shape)
    
#     i = i.flatten()
#     j = j.flatten()
#     k = k.flatten()
#     nodes = list(zip(i,j,k))
#     valid_nodes = [(x,y,z) for (x,y,z) in nodes if z != -1]
#     x,y,z = zip(*valid_nodes)
#     result = np.zeros((300,300,10))
#     result[x,y,z] = 1
    
#     return result

In [ ]:
# ### V Visualization
# import pyvista as pv
# pv.global_theme.notebook = False
# p = pv.Plotter()

# for (i, polygon) in enumerate(POLYGONS):
#     p.add_mesh(polygon, show_edges=True, opacity=0.5, color="w", lighting=False)

# for (i, points) in enumerate(POINTS):
#     intersection = pv.PolyData(points)
#     try:
#         p.add_mesh(intersection, color="maroon", point_size=25, label="Intersection Points")
#     except:
#         pass

# # for (i, ray) in enumerate(RAYS):
# #     p.add_mesh(ray, color="blue", line_width=5, label="Ray Segment n{}".format(i))

# p.show_bounds()
# # p.add_legend()
# p.show()